In [109]:
with open ("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()
print("total characters:", len(raw_text))
print(raw_text[:99])    

total characters: 20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


In [110]:
import re
tokens = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
print(tokens)

['I', ' ', 'HAD', ' ', 'always', ' ', 'thought', ' ', 'Jack', ' ', 'Gisburn', ' ', 'rather', ' ', 'a', ' ', 'cheap', ' ', 'genius', '--', 'though', ' ', 'a', ' ', 'good', ' ', 'fellow', ' ', 'enough', '--', 'so', ' ', 'it', ' ', 'was', ' ', 'no', ' ', 'great', ' ', 'surprise', ' ', 'to', ' ', 'me', ' ', 'to', ' ', 'hear', ' ', 'that', ',', '', ' ', 'in', ' ', 'the', ' ', 'height', ' ', 'of', ' ', 'his', ' ', 'glory', ',', '', ' ', 'he', ' ', 'had', ' ', 'dropped', ' ', 'his', ' ', 'painting', ',', '', ' ', 'married', ' ', 'a', ' ', 'rich', ' ', 'widow', ',', '', ' ', 'and', ' ', 'established', ' ', 'himself', ' ', 'in', ' ', 'a', ' ', 'villa', ' ', 'on', ' ', 'the', ' ', 'Riviera', '.', '', ' ', '', '(', 'Though', ' ', 'I', ' ', 'rather', ' ', 'thought', ' ', 'it', ' ', 'would', ' ', 'have', ' ', 'been', ' ', 'Rome', ' ', 'or', ' ', 'Florence', '.', '', ')', '', '\n', '', '\n', '', '"', 'The', ' ', 'height', ' ', 'of', ' ', 'his', ' ', 'glory', '"', '', '--', 'that', ' ', 'was', ' ', '

In [111]:
# use strip to remove whitespaces
preprocessed = [item for item in tokens if item.strip()]
print(preprocessed)
print(len(preprocessed))

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(', 'Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"', 'The', 'height', 'of', 'his', 'glory', '"', '--', 'that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing', '--', 'his', 'last', 'Chicago', 'sitter', '--', 'deploring', 'his', 'unaccountable', 'abdication', '.', '"', 'Of', 'course', 'it', "'", 's', 'going', 'to', 'send', 'the', 'value', 'of', 'my', 'picture', "'", 'way', 'up', ';', 'but', 'I', 'don', "'", 't', 'think', 'of', 'that', ',

In [112]:
all_words = sorted(set(preprocessed))
print(len(all_words))

1130


In [113]:
all_words = list(set(preprocessed))
all_words.extend(["<|endoftext|>", "<|unk|>"])
print(len(all_words))

1132


In [114]:
vocab = {token: integer for integer, token in enumerate(all_words)}
print(vocab)

{'circumstance': 0, 'glanced': 1, 'apparent': 2, 'head': 3, 'resources': 4, 'sweetly': 5, 'varnishing': 6, 'You': 7, 'appeared': 8, 'pathos': 9, 'three': 10, 'people': 11, 'know': 12, 'began': 13, 'away': 14, 'cigarette': 15, 'Jack': 16, 'technicalities': 17, 'says': 18, 'Hermia': 19, 'adulation': 20, 'latter': 21, 'tinge': 22, 'colour': 23, 'superb': 24, 'laugh': 25, 'phrase': 26, 'hour': 27, 'answered': 28, 'rs': 29, 'Claude': 30, 'distinguished': 31, 'died': 32, 'wants': 33, 'Rome': 34, 'footstep': 35, 'threw': 36, 'shaking': 37, 'amazement': 38, 'patient': 39, 'don': 40, 'none': 41, 'easel': 42, 'much': 43, 'happened': 44, 'Had': 45, 'idling': 46, 'Why': 47, 'central': 48, 'touched': 49, 'portrait': 50, 'liked': 51, 'got': 52, 'brings': 53, 'want': 54, 'hadn': 55, 'canvases': 56, 'abruptly': 57, 'never': 58, 'simpleton': 59, 'quickly': 60, 'high': 61, 'presenting': 62, 'set': 63, 'enough': 64, 'real': 65, 'would': 66, 'hermit': 67, 'out': 68, 'only': 69, 'silent': 70, 'reassurance'

In [77]:
class SimpleTokennizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s, i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)

        preprocessed = [
            item.strip()for item in preprocessed if item.strip()
        ]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text



In [78]:
tokkennizer = SimpleTokennizerV1(vocab)
text = """"It's the last he painted, you know," 
           Mrs. Gisburn said with pardonable pride."""
ids = tokkennizer.encode(text)
print(ids)

[314, 524, 707, 132, 653, 619, 943, 310, 507, 109, 12, 507, 314, 286, 579, 87, 599, 304, 1096, 918, 579]


In [79]:
converted_text=tokkennizer.decode(ids)
print(converted_text)

" It' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.


In [61]:
tokkennizer.encode("Hello, how are you!")

KeyError: 'Hello'

In [80]:
class SimpleTokenzire2:
    def __init__(self,vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s, i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        preprocessed = [
            item if item in self.str_to_int
            else "<|unk|>" for item in preprocessed
        ]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    
    def decode(self, ids):
        text = " ".join(self.int_to_str[i] for i in ids)
        text = re.sub(r'\s+([,.:;?!"()\'])', r'\1', text)
        return text

In [88]:
for i,item in enumerate(list(vocab.items())[-5:]):
    print(item)


('familiar', 1127)
('resented', 1128)
('same', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [96]:
tokenzier = SimpleTokenzire2(vocab)
text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."

text = " <|endoftext|> ".join((text1,text2))
print(text)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.


In [97]:
ids = tokenzier.encode(text)
print(ids)

[1131, 507, 828, 109, 546, 1051, 608, 1130, 698, 653, 548, 410, 754, 653, 1131, 579]


In [98]:
text = tokenzier.decode(ids)
print(text)

<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.


In [99]:
! pip3 install tiktoken

   -------------------------------------- 884.2/884.2 kB 323.3 kB/s eta 0:00:00



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
import importlib
import importlib.metadata
import tiktoken
print("tiktoken version",importlib.metadata.version("tiktoken"))

tiktoken version 0.8.0


In [13]:
tokenizer = tiktoken.get_encoding("gpt2")

In [105]:
text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
     "of someunknownPlace."
)

integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})

print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


In [106]:
txt = tokenizer.decode(integers)
print(txt)

Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.


In [118]:
enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

5145


In [119]:
enc_sample = enc_text[50:]

In [120]:
#context size determines how many tokens are included in the input
context_size = 4

x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]

print(f"x: {x}")
print(f"y: {y}")

x: [290, 4920, 2241, 287]
y: [4920, 2241, 287, 257]


In [121]:
for i in range(1,context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(f"context {context}-------> desired {desired}")

context [290]-------> desired 4920
context [290, 4920]-------> desired 2241
context [290, 4920, 2241]-------> desired 287
context [290, 4920, 2241, 287]-------> desired 257


In [130]:
for i in range(1,context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(tokenizer.decode(context) ,"--------->", tokenizer.decode([desired]))

 and --------->  established
 and established --------->  himself
 and established himself --------->  in
 and established himself in --------->  a


In [4]:
from torch.utils.data import Dataset, DataLoader    

class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

In [9]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [10]:
with open("the-verdict.txt","r",encoding="utf-8") as f:
    raw_text = f.read()

In [14]:
import torch
print("PyTorch version:", torch.__version__)
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

PyTorch version: 1.12.1+cpu
[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [15]:
input_ids = torch.tensor([2,3,5,1])

In [16]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [18]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [21]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [22]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


In [32]:
vocab_size = 50287
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)


In [25]:
print(token_embedding_layer.weight)

Parameter containing:
tensor([[-2.1338,  1.0524, -0.3885,  ...,  0.2461,  1.2119,  0.3171],
        [ 1.2277, -0.4297, -2.2121,  ..., -0.1640, -0.3348, -0.0221],
        [ 1.3382,  0.2706,  0.5071,  ...,  0.0175, -2.1517,  0.3924],
        ...,
        [ 0.8206,  0.6397, -0.0352,  ...,  0.5263, -0.3815, -0.8283],
        [-0.2191, -0.0580, -0.1796,  ..., -1.5490, -1.1536, -0.0087],
        [ 1.8189,  0.4759,  0.5786,  ...,  0.3672, -0.3833,  0.3321]],
       requires_grad=True)


In [33]:
max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length, stride=max_length, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)

In [34]:
print("Token ids:", inputs)
print("\nInput shape:", inputs.shape)

Token ids: tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Input shape: torch.Size([8, 4])


In [37]:
token_embedding = token_embedding_layer(inputs)
print(token_embedding.shape)

torch.Size([8, 4, 256])


In [40]:
context_length = max_length
positional_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [42]:
positional_embedding = positional_embedding_layer(torch.arange(max_length))
print(positional_embedding.shape)

torch.Size([4, 256])


In [44]:
input_embedding  = token_embedding + positional_embedding
print(input_embedding.shape)

torch.Size([8, 4, 256])
